name: fluttrim_core
description: Pure Dart business logic for fluttrim (scan/plan/apply with safety rules).
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.10.0

# Add regular dependencies here.
dependencies:
  glob: ^2.1.2
  path: ^1.9.0
  yaml: ^3.1.2

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
